### ISSUE TITLE
horizontal register overflows container

### ISSUE THREAD

**Issue by davidsteinberger** [PredixDev/px-vis-pie-chart#31] opened 2017-03-07 13:52 UTC
## Expected behavior and actual behavior:

As a user I'd expect the register to properly position and overflow for any reasonable amount of slices properly. But in any of the v1.x.x versions, the register may overflow the container.

The issue is related to #19. However, I'd argue that this is not an enhancement, rather a bug.

## Steps to reproduce the problem:

Use any v1.x.x version of px-vis-pie with a few sections and set 
    
    register-config='{"width":200,"type":"horizontal"}' 

If required I can create a simple demo.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

any v1.x.x

## Screenshots (_optional, but very helpful_):

![screen shot 2017-03-07 at 14 38 34](https://cloud.githubusercontent.com/assets/385430/23659065/35eb41b2-0345-11e7-9c5b-4598f5536949.png)

**Comment by benoitjchevalier** [comment] 2017-03-07 14:58
Hello,

Thanks for the feedback. Just to clarify, you are expecting the register to get scrollbar when bigger than the container but it does not, is that right?

**Comment by davidsteinberger** [comment] 2017-03-07 15:17
I wouldn't go that far to say it has to be scrollbar (I'm a bad designer ;-)), but that would be the easiest option I guess (if I recall correctly Highcharts adds buttons that allow users to vertically scroll through the register). 

But if we go with the scrollbar option, then I think we should also double check that the register is horizontally centered within the chart. The current API allows to provide `width` and `registerConfig.width` and they may not be the same. So the container of `div#registerWrap` may also need a `justify-content: center;` in that case, isn't it?

**Comment by benoitjchevalier** [comment] 2017-03-08 00:49
Turns out the pie registers were a bit behind and lacked some of the enhancements other registers have benefited from. 

I've made sure the scrollbar will show up and corrected how the value is displayed (it should be below the name rather than next to it). I've also added the dynamic menus to them to be consistent with other charts

I've also ended up adding an `horizontalAlignment` to all registers so that when they're horizontal the dev can choose the positioning (following flex: `left` `right` `center` `justify` `spaced`). One thing leading to another I made various changes to the flex layout of the pie chart... Hopefully everything should be good :)

**Comment by davidsteinberger** [comment] 2017-03-08 13:11
The positioning works well. Thanks for that!

But the overflow does not work for me. Don't you think that `width` should also be passed onto `<px-vis-register>`? In addition to that I also need `overflow: auto;` (at least in FF and Chrome) to make it overflow nice. You can see the behavior by changing your _dev.html_ to something like:

    <div style="height:800px; width: 400px; background-color: salmon">
      <px-vis-pie-chart
        chart-data="{{data}}"
        height="500"
        width="200"
        prevent-resize
        ...
    ...

**Comment by benoitjchevalier** [comment] 2017-03-08 16:44
The width of the chart is passed down to the register through `chartWidth`, which is then use by the register to try and determine if it needs scrollbars. The `overflow:auto` is coming as part of the class added when the register has scrollbars: `scrollOn`.

In your example I think you would need to remove the `prevent-resize` so that the chart tries to match the salmon container size. However in this example I still see scrollbars even though the chart spills out of the container.

Just double checking, did you also pull the latest vis master when re-testing this issue? Let me know if you can reproduce the issue.

ps: some of the register sizing behavior can be a bit unintuitive at the moment, and in particular the pie registers might behave slightly differently than other charts. For example for other charts `registerConfig.width` will be ignored if the register is horizontal, in order for the register to try and match the size of the chart. In the pie chart it will *not* be ignored. Eventually I think that we can cover all scenarios by playing with different parameters (register width, chart width, margins, prevent resize) but I'd like to revisit how this works and make it more intuitive/consistent but won't have time given how close we are to the release.

**Comment by davidsteinberger** [comment] 2017-03-08 17:08
Crap, I did not update px-vis this time (was on some beta here but not latest master). It works well on latest master.

**Comment by benoitjchevalier** [comment] 2017-03-08 17:14
sweet 👍

**Comment by benoitjchevalier** [comment] 2017-03-10 20:34
Fixed with 1.0.0 release

**Closed as completed by benoitjchevalier** 2017-03-10 20:34 UTC
